import { mysqlTable, text, int, tinyint, serial, timestamp, float } from 'drizzle-orm/mysql-core';

export const account = mysqlTable('account', {
    id: serial().primaryKey(),
    username: text().notNull().unique(),
    salt: text().notNull(),
    verifier: text().notNull(),
    session_key: text(),
    totp_secret: text(),
    email: text().notNull().default(''),
    reg_mail: text().notNull().default(''),
    joindate: timestamp().notNull().defaultNow(),
    last_ip: text().notNull().default('127.0.0.1'),
    last_attempt_ip: text().notNull().default('127.0.0.1'),
    failed_logins: int().notNull().default(0),
    locked: tinyint().notNull().default(0),
    lock_country: text().notNull().default('00'),
    last_login: timestamp(),
    online: tinyint().notNull().default(0),
    expansion: tinyint().notNull().default(2),
    Flags: int().notNull().default(0),
    mutereason: text().notNull().default(''),
    muteby: text().notNull().default(''),
    locale: tinyint().notNull().default(0),
    os: text().notNull().default(''),
    recruiter: int().notNull().default(0),
    totaltime: int().notNull().default(0)
})

export const realmlist = mysqlTable('realmlist', {
    id: serial().primaryKey(),
    name: text().notNull().default(''),
    address: text().notNull().default('127.0.0.1'),
    localAddress: text().notNull().default('127.0.0.1'),
    localSubnetMask: text().notNull().default('255.255.255.0'),
    port: int().notNull().default(8085),
    icon: int().notNull().default(0),
    flag: int().notNull().default(2),
    timezone: int().notNull().default(0),
    allowedSecurityLevel: int().notNull().default(0),
    population: float().notNull().default(0),
    gamebuild: int().notNull().default(12340)
})

export const realmcharacters = mysqlTable('realmcharacters', {
    realmid: int().notNull(),
    acctid: int().notNull(),
    numchars: tinyint().notNull(),
});

export const characters = mysqlTable('characters', {
    guid: int().notNull().default(0).primaryKey(),
    account: int().notNull().default(0),
    name: text().notNull().default(''),
    race: tinyint().notNull().default(0),
    class: tinyint().notNull().default(0),
    gender: tinyint().notNull().default(0),
    level: tinyint().notNull().default(0),
    xp: int().notNull().default(0),
    money: int().notNull().default(0),
    skin: tinyint().notNull().default(0),
    face: tinyint().notNull().default(0),
    hairStyle: tinyint().notNull().default(0),
    hairColor: tinyint().notNull().default(0),
    facialStyle: tinyint().notNull().default(0),
    bankSlots: tinyint().notNull().default(0),
    restState: tinyint().notNull().default(0),
    playerFlags: int().notNull().default(0),
    position_x: float().notNull().default(0),
    position_y: float().notNull().default(0),
    position_z: float().notNull().default(0),
    map: int().notNull().default(0),
    instance_id: int().notNull().default(0),
    instance_mode_mask: tinyint().notNull().default(0),
    orientation: float().notNull().default(0),
    taximask: text().notNull().default(''),
    online: tinyint().notNull().default(0),
    cinematic: tinyint().notNull().default(0),
    totaltime: int().notNull().default(0),
    leveltime: int().notNull().default(0),
    logout_time: int().notNull().default(0),
    is_logout_resting: tinyint().notNull().default(0),
    rest_bonus: float().notNull().default(0),
    resettalents_cost: int().notNull().default(0),
    resettalents_time: int().notNull().default(0),
    trans_x: float().notNull().default(0),
    trans_y: float().notNull().default(0),
    trans_z: float().notNull().default(0),
    trans_o: float().notNull().default(0),
    transguid: int().default(0),
    extra_flags: int().notNull().default(0),
    stable_slots: tinyint().notNull().default(0),
    at_login: tinyint().notNull().default(0),
    zone: int().notNull().default(0),
    death_expire_time: int().notNull().default(0),
    taxi_path: text(),
    arenaPoints: int().notNull().default(0),
    totalHonorPoints: int().notNull().default(0),
    todayHonorPoints: int().notNull().default(0),
    yesterdayHonorPoints: int().notNull().default(0),
    totalKills: int().notNull().default(0),
    todayKills: tinyint().notNull().default(0),
    yesterdayKills: tinyint().notNull().default(0),
    chosenTitle: int().notNull().default(0),
    knownCurrencies: int().notNull().default(0),
    watchedFaction: int().notNull().default(0),
    drunk: tinyint().notNull().default(0),
    health: int().notNull().default(0),
    power1: int().notNull().default(0),
    power2: int().notNull().default(0),
    power3: int().notNull().default(0),
    power4: int().notNull().default(0),
    power5: int().notNull().default(0),
    power6: int().notNull().default(0),
    power7: int().notNull().default(0),
    latency: int().default(0),
    talentGroupsCount: tinyint().notNull().default(1),
    activeTalentGroup: tinyint().notNull().default(0),
    exploredZones: text(),
    equipmentCache: text(),
    ammoId: int().notNull().default(0),
    knownTitles: text(),
    actionBars: tinyint().notNull().default(0),
    grantableLevels: tinyint().notNull().default(0),
    order: tinyint(),
    creation_date: timestamp().notNull().defaultNow(),
    deleteInfos_Account: int(),
    deleteInfos_Name: text(),
    deleteDate: int(),
    innTriggerId: int().notNull(),
    extraBonusTalentCount: int().notNull().default(0),
});